print("hello world")

In [1]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [44]:
a=23+ 6j
type(a)

complex

In [50]:
b=True
type(b)

bool

In [17]:
#tuple
t=(5,7.9,True,7+4j)
type(t)

AttributeError: 'tuple' object has no attribute 'append'

In [11]:
#list
a=[34,78,89]
a[2]=45
a.append(566)
print(a)


[34, 78, 45, 566]


In [65]:
#dictionary
a={'a':56,'b':67}
type(a)

dict

In [23]:
a="""asdsad sadfsa sadsadsadawsdasd
dsfsdf fedsfesf"""
print(a)


asdsad sadfsa sadsadsadawsdasd
dsfsdf fedsfesf


In [65]:
a='table'
a[1:4:2]

'al'

In [29]:
a='welcome to cttc'
a[3:10:3]

'ceo'

In [41]:
s='HelLo World'
s.capitalize()

'Hello world'

In [43]:
s='HelLo World'
s.upper()

'HELLO WORLD'

In [45]:
s='HelLo World'
s.lower()

'hello world'

In [49]:
s='HelLo World abc'
s.title()

'Hello World Abc'

In [51]:
s='HelLo World'
s.isupper()

False

In [61]:
s='HELLO WORLS'
s.isupper()

True

In [57]:
s='HelLo World'
s.swapcase()

'hELlO wORLD'

In [63]:
s='HelLo World'
s.center(30)

'         HelLo World          '

In [69]:
'aaaaa@bbbbbb'.split('@')


['aaaaa', 'bbbbbb']

In [3]:
'aaaaa@bbbbbb'.join(['ccc','ddd','fff','kkk'])

'cccaaaaa@bbbbbbdddaaaaa@bbbbbbfffaaaaa@bbbbbbkkk'

In [79]:
'1234'.isdigit()

True

In [81]:
'123abc'.isalnum()

True

In [85]:
s.startswith(h)

NameError: name 'h' is not defined

In [93]:
s='abc'    #strings are imutable changes cannot be done if done only to that shell 
s[1]='r'
print(s)


TypeError: 'str' object does not support item assignment

In [97]:
l=[12,89.7,'Table',True]
l.append("aaa")
l[2]=99
print(l)

[12, 89.7, 99, True, 'aaa']


In [17]:
l=[12,89.7,'Table',True]
l.insert(2,777)
print(l)


[12, 89.7, 777, 'Table', True]


In [111]:
a=89
b=78
print(a)
b

89


78

In [9]:
l=[12,89.7,'Table',True]
l.extend([199,67,10])
print(l)

[12, 89.7, 'Table', True, 199, 67, 10]


In [21]:
l=[12,89.7,'Table',12,True]
l.remove(12) #remove first element
print(l)


[89.7, 'Table', 12, True]


In [131]:
l=[12,89.7,'Table',12,True]
l.count(12)


2

In [33]:
l={12,89.7,12,78,90,78,78,78}
print(l)

{89.7, 90, 12, 78}


In [148]:
l=[12,89.7,12,78,90]
l.sort(reverse=True)
print(l)

[90, 89.7, 78, 12, 12]


In [156]:
#tupple attribute
t=(28,28,89.7,'Table',False)
t.count(28)
t.index


2

In [158]:
t[2:4:]


(89.7, 'Table')

In [160]:
t[0::2]

(28, 89.7, False)

In [164]:
t.index(28)

0

In [3]:
#homogenous
s1={1,2,3,4,5,6,7,8,9,0}
type(s1)

set

In [5]:
#heterogenous
s1={'siva',89.1,'om',True}
type(s1)

set

In [11]:
s2={1,2,3,4,5,6,2}
s3={'siva',89.1,'sneha',True,2}
s2.union(s3)

{1, 2, 3, 4, 5, 6, 89.1, 'siva', 'sneha'}

In [35]:
s2={1,2,3,4,5,6}
s3={'siva',89.1,'sneha',True,2}
s2.difference(s3)

{3, 4, 5, 6}

In [39]:
s1={1,2,3,4,5,6}
s2={'apple','z',7,8,9}
s1.isdisjoint(s2)

True

In [23]:
s1={1,2,3,4,5}
s2={4,5}
s2.issubset(s1)

True

In [27]:
x={1,2,3,4,5}
x.add('sneha')
x

{1, 2, 3, 4, 5, 'sneha'}

In [31]:
a={1,2,3,4,5,6}
a.pop()
a

{2, 3, 4, 5, 6}

In [ ]:
dictionary



In [45]:
d={1:'100','A':'aeroplane','B':'mani','c':'siva'}
d.values() 

NameError: name 'siva' is not defined

In [47]:
d={1:'100','A':'aeroplane','B':'mani','c':'  siva'}
d.items()

dict_items([(1, '100'), ('A', 'aeroplane'), ('B', 'mani'), ('c', '  siva')])

In [67]:
d={1:'100','A':'aeroplane','B':'mani','c':'  siva'}
d.update({12:'sneha'})
print(d)

{1: '100', 'A': 'aeroplane', 'B': 'mani', 'c': '  siva', 12: 'sneha'}


In [57]:
d={1:'100','A':'aeroplane','B':'mani','c':'  siva',12:'sneha'}
d.pop(12)
d

{1: '100', 'A': 'aeroplane', 'B': 'mani', 'c': '  siva'}

In [ ]:
'an operator is a special symbols upon which we perform some operations on variables and values'

In [ ]:
membership operators

in:True if var is the sequence.
False if var is not in the sequence

In [73]:
x=int(input("enter the age"))
if(x>18 ):
    print("allowed to vote")
else:
    print("not allowed")


enter the age 23


allowed to vote


In [79]:
a=input("enter the character")
if a=='a' or a=='e' or a=='i' or a=='o' or a=='u':
    print("it is a vowel")
else:
    print("not a vowel")
    


enter the character d


not a vowel


In [15]:
X=input("enter the character")
a='aeiouAEIOU'
if X in a:
    print("it is a vowel")
else:
    print("not a vowel")
    


enter the character t


not a vowel


In [5]:
a=260
b=260
a is b

False

In [28]:
tenth=int(input('enter 10th percentage'))
twelve=int(input('enter 12th percentage'))
btech=int(input('enter b.tech percentage'))
if tenth>60:
    if twelve>60:
        if btech>70:
            print('you are eligible for scholarship')
else:
    print('you are not eligible for scolarship')
    

enter 10th percentage 70
enter 12th percentage 70
enter b.tech percentage 77


you are eligible for scholarship


In [ ]:
tenth=int(input('enter 10th percentage'))
if tenth>60:
    twelve=int(input('enter 12th percentage'))
    if twelve>60:
        btech=int(input('enter b.tech percentage'))
                if btech>70:
                    print('you are eligible for scholarship')
  
else:
    print('you are not eligible for scolarship')
    



In [34]:
x=int(input("enter the number"))
if x>0:
    print('no is positive')
    
else:
    print('no is negative')
if x%2==0:
        print('no is even')
else:
        print ('no is odd')


enter the number 56


no is positive
no is even


In [38]:
x=int(input('enter the no'))
if(x==0):
    print("monday")
elif(x==1):
    print('tuesday')
elif(x==2):
    print('wednesday')
elif(x==3):
    print('thursday')
elif(x==4):
    print('friday')
elif(x==5):
    print('saturday')
elif(x==6):
    print('sunday')
else:
    print('enter btw 0 to 6')

enter the no 6


sunday


In [5]:
for x in range(200,101,-1):
    if(x%3==0):
        print(x)

198
195
192
189
186
183
180
177
174
171
168
165
162
159
156
153
150
147
144
141
138
135
132
129
126
123
120
117
114
111
108
105
102


In [46]:
x=int(input("enter the number"))
for i in range(1,11):
    print(x*i)
      

enter the number 5


5
10
15
20
25
30
35
40
45
50


In [98]:
#to check weather the enter number is prime or not
x=int(input("enter the number"))
y=0
for i in range(2,x):
    if x%i==0:
        y=y+1
if y==0:
    print("no is a prime no")
else :
    print("the number is not a prime  number")

enter the number 66


the number is not a prime  number


In [13]:
#to check weather the enter number is prime or not
for i in range(50,201):
    y=0
    for j in range(2,i):
        if i%j==0:
          y=y+1
    if y==0:
      print(i, " is a prime no")
    else :
      print("the number",i," is not a prime  number")
    


the number 50  is not a prime  number
the number 51  is not a prime  number
the number 52  is not a prime  number
53  is a prime no
the number 54  is not a prime  number
the number 55  is not a prime  number
the number 56  is not a prime  number
the number 57  is not a prime  number
the number 58  is not a prime  number
59  is a prime no
the number 60  is not a prime  number
61  is a prime no
the number 62  is not a prime  number
the number 63  is not a prime  number
the number 64  is not a prime  number
the number 65  is not a prime  number
the number 66  is not a prime  number
67  is a prime no
the number 68  is not a prime  number
the number 69  is not a prime  number
the number 70  is not a prime  number
71  is a prime no
the number 72  is not a prime  number
73  is a prime no
the number 74  is not a prime  number
the number 75  is not a prime  number
the number 76  is not a prime  number
the number 77  is not a prime  number
the number 78  is not a prime  number
79  is a prime no


In [28]:
x=int(input("enter the  number"))
y=1
while y<11:
    print(x,"x",y,"=",x*y)
    y+=1
    

enter the  number 6


6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


In [44]:
x=int(input("enter the number"))
y=2
z=0
while(y<x):
    if x%y==0:
        z+=1
    y+=1
if z==0:
    print("prime number")
else:
    print("not a prime number")

enter the number 19


prime number


In [56]:
a=50
while a<201:
    y=2
    z=0
    while(y<a):
        if a%y==0:
            z+=1
        y+=1
    if z==0:
        print(a ,"is a prime number")
    else:
        print(a ,"is not a prime number")
    a+=1

50 is not a prime number
51 is not a prime number
52 is not a prime number
53 is a prime number
54 is not a prime number
55 is not a prime number
56 is not a prime number
57 is not a prime number
58 is not a prime number
59 is a prime number
60 is not a prime number
61 is a prime number
62 is not a prime number
63 is not a prime number
64 is not a prime number
65 is not a prime number
66 is not a prime number
67 is a prime number
68 is not a prime number
69 is not a prime number
70 is not a prime number
71 is a prime number
72 is not a prime number
73 is a prime number
74 is not a prime number
75 is not a prime number
76 is not a prime number
77 is not a prime number
78 is not a prime number
79 is a prime number
80 is not a prime number
81 is not a prime number
82 is not a prime number
83 is a prime number
84 is not a prime number
85 is not a prime number
86 is not a prime number
87 is not a prime number
88 is not a prime number
89 is a prime number
90 is not a prime number
91 is not a

In [61]:
#numpy

import numpy as np
#1-D array
a=np.array([2,7,3,9,4])
print(type(a))
a


<class 'numpy.ndarray'>


array([2, 7, 3, 9, 4])

In [13]:
b=np.array([2,'cat',23.5,True])
b


array(['2', 'cat', '23.5', 'True'], dtype='<U32')

In [17]:
b=np.array([25,34.5,20,True])
b

array([25. , 34.5, 20. ,  1. ])

In [9]:
b1=([
      [23,10,15],
      [45,78,981]
   ])
b1[1][2]

981

In [73]:
b2=np.array([
    [23,10,15],
    [45,78,91],
    [40,76,99]
           ])
b2[1][2]

91

In [67]:
#array attributes
b2.shape

(3, 3)

In [19]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.arange(1,17,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [27]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [35]:
np.zeros((6,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.twos((4,5))

AttributeError: module 'numpy' has no attribute 'twos'

In [43]:
np.full((4,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [45]:
np.full((6,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [51]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [61]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [69]:
np.linspace(1,20,21)

array([ 1.  ,  1.95,  2.9 ,  3.85,  4.8 ,  5.75,  6.7 ,  7.65,  8.6 ,
        9.55, 10.5 , 11.45, 12.4 , 13.35, 14.3 , 15.25, 16.2 , 17.15,
       18.1 , 19.05, 20.  ])

In [71]:
np.linspace(1,50,20)

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [73]:
np.linspace(1,20,30)

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [122]:
np.random.rand()# random no btw 0 to 1

0.2384166516936198

In [120]:
np.random.rand(5)

array([0.06099365, 0.91218936, 0.07742362, 0.42850131, 0.84242836])

In [114]:
np.random.rand(3,4)

array([[0.61335227, 0.6271698 , 0.85722372, 0.67924916],
       [0.89148989, 0.24064944, 0.7857162 , 0.48174564],
       [0.11411275, 0.77519607, 0.43866532, 0.60057211]])

In [ ]:
int(np.random.rand()*10)

In [141]:
np.random.randint(5)

4

In [143]:
np.random.randint(1,20,5) #from 1 to 20 -> 5 random no

array([17,  9, 17,  4, 16])

In [145]:
np.random.randint(1,100,(4,5)) # 4*5 matrix of random number

array([[54, 22, 53, 61, 71],
       [79, 58, 53, 15, 88],
       [56, 65, 12, 44, 45],
       [62, 27, 54, 32, 29]])

In [153]:
a=np.array([30,55,79,25,30])
b=np.array([40,4,5,66,2])
np.add(a,b)

array([70, 59, 84, 91, 32])

In [155]:
np.subtract(a,b)

array([-10,  51,  74, -41,  28])

In [159]:
np.divide(a,b)

array([ 0.75      , 13.75      , 15.8       ,  0.37878788, 15.        ])

In [161]:
np.multiply(a,b)

array([1200,  220,  395, 1650,   60])

In [163]:
np.mod(a,b) # remainder

array([30,  3,  4, 25,  0])

In [165]:
np.log(b)

array([3.68887945, 1.38629436, 1.60943791, 4.18965474, 0.69314718])

In [167]:
np.sqrt(a)

array([5.47722558, 7.41619849, 8.88819442, 5.        , 5.47722558])

In [169]:
print(b)
np.power(b,3)

[40  4  5 66  2]


array([ 64000,     64,    125, 287496,      8], dtype=int32)

In [171]:
np.sin(a)

array([-0.98803162, -0.99975517, -0.44411267, -0.13235175, -0.98803162])

In [173]:
np.cos(a)

array([ 0.15425145,  0.02212676, -0.89597095,  0.99120281,  0.15425145])

In [175]:
np.tan(a)

array([ -6.4053312 , -45.18308791,   0.49567753,  -0.13352641,
        -6.4053312 ])

In [177]:
#np.cot xxx 
1/np.tan(a)

array([-0.15611995, -0.02213217,  2.01744064, -7.48915531, -0.15611995])

In [183]:
print(a)
np.max(a)

[30 55 79 25 30]


79

In [185]:
np.min(a)

25

In [187]:
np.mean(a)

43.8

In [189]:
np.median(a)

30.0

In [191]:
np.std(a)

20.488045294756645

In [193]:
np.var(a)

419.75999999999993

In [195]:
c=np.array([10,20,30,40])
np.repeat(c,4)

array([10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30, 30, 40, 40, 40, 40])

In [197]:
np.tile(c,4)

array([10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40])

In [201]:
d=np.array([1,2,3,5,4,3,2,6,7,3])
np.where(d==3)

(array([2, 5, 9], dtype=int64),)

In [203]:
a=np.array([30,65,55,79,25])
np.argmax(a)  # position of the highest value

3

In [205]:
np.argmin(a)
# position of the minimum value

4

In [209]:
a=np.array([[2,3],[2,4]])
b=np.array([[3,5],[1,5]])
np.dot(a,b)

array([[ 9, 25],
       [10, 30]])

In [211]:
a=np.array([60,30,25,49,2,9,12])
a

array([60, 30, 25, 49,  2,  9, 12])

In [213]:
#indexing and slicing in 2d array
b=np.random.randint(1,25,(5,5))
b

array([[15,  2, 15,  4,  6],
       [10,  7,  3,  2,  2],
       [15, 11, 16, 20, 12],
       [ 9, 22,  5,  5, 12],
       [19,  2,  8,  6,  1]])

In [215]:
b[1,3]

2

In [217]:
#row slicing: [start:stop+1:step]
#column slicing : [start:stop+1:step]
#syntax : var [row_slicing, col_slicing]
print(b)
b[1:4:1,0:5:2]

[[15  2 15  4  6]
 [10  7  3  2  2]
 [15 11 16 20 12]
 [ 9 22  5  5 12]
 [19  2  8  6  1]]


array([[10,  3,  2],
       [15, 16, 12],
       [ 9,  5, 12]])

In [223]:
a=np.array([[2,3],[2,4]])
b=np.array([[3,5],[1,5]])
np.concatenate((a,b),axis=1)

array([[2, 3, 3, 5],
       [2, 4, 1, 5]])

In [225]:
a=np.array([[2,3],[2,4]])
b=np.array([[3,5],[1,5]])
np.concatenate((a,b),axis=0)

array([[2, 3],
       [2, 4],
       [3, 5],
       [1, 5]])

In [19]:
import pandas as pd
import numpy as np

In [81]:
#creating series
s = pd.Series(['a','b','d','f','e'])
s

0    a
1    b
2    d
3    f
4    e
dtype: object

In [83]:
s = pd.Series(['a','b','d','f','e'],index=[10,20,30,40,50])
s

10    a
20    b
30    d
40    f
50    e
dtype: object

In [85]:
s[50]

'e'

In [13]:
s[30]

'd'

In [15]:
s[1:3:1] #slicing

20    b
30    d
dtype: object

In [21]:
#tuple to series
t = pd.Series((10,20,30,50,90),index=[10,20,30,40,50])
t

10    10
20    20
30    30
40    50
50    90
dtype: int64

In [15]:
t[1:3:1]

NameError: name 't' is not defined

In [25]:
#array to series
a = np.array([20,30,38,90,80,18])
s = pd.Series(a)
s

0    20
1    30
2    38
3    90
4    80
5    18
dtype: int32

In [29]:
#set to series
a = pd.Series((10,20,40,50,80))
a

0    10
1    20
2    40
3    50
4    80
dtype: int64

In [25]:
#dictionary to series
d = pd.Series({'a':1,'b':2,'c':3,'d':4})
d

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
d1 = pd.Series({'a':1,'b':2,'c':3,'d':4},index=['c','a','f','b','l'])
d1

c    3.0
a    1.0
f    NaN
b    2.0
l    NaN
dtype: float64

In [31]:
d1['f']

nan

In [37]:
d1['a']

1.0

In [39]:
d['a']

1

In [41]:
d[2]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8044\464593666.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[2]


3

In [43]:
print(d)

a    1
b    2
c    3
d    4
dtype: int64


In [45]:
d[1:5:2]

b    2
d    4
dtype: int64

In [47]:
d['b':'d':2]

b    2
d    4
dtype: int64

In [45]:
#DataFrame
d = {
    'Name': ['Vishnu', 'Ram', 'Sita', 'Gita', 'Hari', 'Krishna', 'Radhe'],
    'Roll': [21, 22, 23, 24, 25, 26, 27],
    'Age':  [23, 21, 25, 24, 23, 19, 20]
}
d

{'Name': ['Vishnu', 'Ram', 'Sita', 'Gita', 'Hari', 'Krishna', 'Radhe'],
 'Roll': [21, 22, 23, 24, 25, 26, 27],
 'Age': [23, 21, 25, 24, 23, 19, 20]}

In [51]:
#dictionary to DataFrame
df = pd.DataFrame(d)
df

Name  Roll  Age
0   Vishnu    21   23
1      Ram    22   21
2     Sita    23   25
3     Gita    24   24
4     Hari    25   23
5  Krishna    26   19
6    Radhe    27   20

In [59]:
df.head() #Data from front side   - .head() returns the first 5 rows of the DataFrame by default.

📌 Syntax
df.head(n)


- n is optional. If provided, it returns the first n rows.
- If not provided, it returns the first 5 rows.



Name  Roll  Age
0  Vishnu    21   23
1     Ram    22   21
2    sita    23   25
3    Gita    24   24
4    Hari    25   23

In [61]:
df.head(2)

Name  Roll  Age
0  Vishnu    21   23
1     Ram    22   21

In [63]:
df.head(7)

Name  Roll  Age
0   Vishnu    21   23
1      Ram    22   21
2     sita    23   25
3     Gita    24   24
4     Hari    25   23
5  Krishna    26   19
6    Radhe    27   20

In [65]:
df.head(10)

Name  Roll  Age
0   Vishnu    21   23
1      Ram    22   21
2     sita    23   25
3     Gita    24   24
4     Hari    25   23
5  Krishna    26   19
6    Radhe    27   20

In [67]:
df.tail(3) #Data from downward to upward

Name  Roll  Age
4     Hari    25   23
5  Krishna    26   19
6    Radhe    27   20

In [71]:
#rename
df = df.rename(columns={'Name':'Student_Name'})
df

Student_Name  Roll  Age
0       Vishnu    21   23
1          Ram    22   21
2         sita    23   25
3         Gita    24   24
4         Hari    25   23
5      Krishna    26   19
6        Radhe    27   20

In [73]:
df.Student_Name[4]

'Hari'

In [75]:
df.Roll[3]



24

In [77]:
#set_index
df.set_index('Roll')

Student_Name  Age
Roll                  
21         Vishnu   23
22            Ram   21
23           sita   25
24           Gita   24
25           Hari   23
26        Krishna   19
27          Radhe   20

In [79]:
df

Student_Name  Roll  Age
0       Vishnu    21   23
1          Ram    22   21
2         sita    23   25
3         Gita    24   24
4         Hari    25   23
5      Krishna    26   19
6        Radhe    27   20

In [81]:
#df = df.set_index('Roll')
df.set_index('Roll',inplace=True)
df

Student_Name  Age
Roll                  
21         Vishnu   23
22            Ram   21
23           sita   25
24           Gita   24
25           Hari   23
26        Krishna   19
27          Radhe   20

In [27]:
d = pd.DataFrame({'Days':[1,2,3,4,5,6],
                  'Places':['Puri','Konark','Delhi',np.NaN,'Vizag','Goa'],
                  'Visitors':[6500,4800,8000,4600,7300,6000]})
d

Days  Places  Visitors
0     1    Puri      6500
1     2  Konark      4800
2     3   Delhi      8000
3     4     NaN      4600
4     5   Vizag      7300
5     6     Goa      6000

In [96]:
#check missing values
d.isnull()

Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False   False     False
3  False    True     False
4  False   False     False
5  False   False     False

In [98]:
d.isnull().sum()

Days        0
Places      1
Visitors    0
dtype: int64

In [100]:
d.info() #information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Days      6 non-null      int64 
 1   Places    5 non-null      object
 2   Visitors  6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes


In [110]:
#fillna
d.Places.fillna('puri')

0      Puri
1    Konark
2     Delhi
3      puri
4     Vizag
5       Goa
Name: Places, dtype: object

In [112]:
d

Days  Places  Visitors
0     1    Puri      6500
1     2  Konark      4800
2     3   Delhi      8000
3     4     NaN      4600
4     5   Vizag      7300
5     6     Goa      6000

In [31]:
import warnings#for warnings
warnings.filterwarnings('ignore')
d.Places.fillna('Puri',inplace=True)
d

Days  Places  Visitors
0     1    Puri      6500
1     2  Konark      4800
2     3   Delhi      8000
3     4    Puri      4600
4     5   Vizag      7300
5     6     Goa      6000

In [120]:
#d=d.replace(np.NaN,'Puri')

In [122]:
d

Days  Places  Visitors
0     1    Puri      6500
1     2  Konark      4800
2     3   Delhi      8000
3     4    Puri      4600
4     5   Vizag      7300
5     6     Goa      6000

In [124]:
d.Visitors.replace(4600,5000,inplace=True)
d

Days  Places  Visitors
0     1    Puri      6500
1     2  Konark      4800
2     3   Delhi      8000
3     4    Puri      5000
4     5   Vizag      7300
5     6     Goa      6000

In [126]:
d.Places.unique() #unique value

array(['Puri', 'Konark', 'Delhi', 'Vizag', 'Goa'], dtype=object)

In [128]:
d.Visitors.mean()

6266.666666666667

In [130]:
d.max() #maximum value

Days            6
Places      Vizag
Visitors     8000
dtype: object

In [132]:
d.describe() #Total data except string

Days     Visitors
count  6.000000     6.000000
mean   3.500000  6266.666667
std    1.870829  1261.216344
min    1.000000  4800.000000
25%    2.250000  5250.000000
50%    3.500000  6250.000000
75%    4.750000  7100.000000
max    6.000000  8000.000000

In [134]:
d.describe(include='all') #it includes string

Days Places     Visitors
count   6.000000      6     6.000000
unique       NaN      5          NaN
top          NaN   Puri          NaN
freq         NaN      2          NaN
mean    3.500000    NaN  6266.666667
std     1.870829    NaN  1261.216344
min     1.000000    NaN  4800.000000
25%     2.250000    NaN  5250.000000
50%     3.500000    NaN  6250.000000
75%     4.750000    NaN  7100.000000
max     6.000000    NaN  8000.000000

In [136]:
d.describe(include='O')

Places
count       6
unique      5
top      Puri
freq        2

iris = pd.read_csv(r"D:\3rd year\iris\iris.data")
iris

In [114]:
iris = pd.read_csv(r"C:\Users\Lenovo\Desktop\july aiml\iris\iris.data",header=None) #to bring the written data present in heading down
iris

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [116]:
iris.columns=['SL','SW','PL','PW','Flower Type']
iris

SL   SW   PL   PW     Flower Type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [118]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SL           150 non-null    float64
 1   SW           150 non-null    float64
 2   PL           150 non-null    float64
 3   PW           150 non-null    float64
 4   Flower Type  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [120]:
iris.SL.unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [39]:
iris.columns

Index(['SL', 'SW', 'PL', 'PW', 'Flower Type'], dtype='object')

In [122]:
for i in iris.columns:
    print(i,':','\n',iris[i].unique(),'\n')

SL : 
 [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9] 

SW : 
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6] 

PL : 
 [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2] 

PW : 
 [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3] 

Flower Type : 
 ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica'] 



In [43]:
iris.describe(include='all')

SL          SW          PL          PW  Flower Type
count   150.000000  150.000000  150.000000  150.000000          150
unique         NaN         NaN         NaN         NaN            3
top            NaN         NaN         NaN         NaN  Iris-setosa
freq           NaN         NaN         NaN         NaN           50
mean      5.843333    3.054000    3.758667    1.198667          NaN
std       0.828066    0.433594    1.764420    0.763161          NaN
min       4.300000    2.000000    1.000000    0.100000          NaN
25%       5.100000    2.800000    1.600000    0.300000          NaN
50%       5.800000    3.000000    4.350000    1.300000          NaN
75%       6.400000    3.300000    5.100000    1.800000          NaN
max       7.900000    4.400000    6.900000    2.500000          NaN

In [58]:
iris.columns=['SL','SW','PL','PW','Flower Type']
iris['Flower Type'].value_counts()

Flower Type
Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: count, dtype: int64

In [126]:
iris.drop('Flower Type')

KeyError: "['Flower Type'] not found in axis"

In [85]:
iris.drop('Flower Type',axis=1)

SL   PL   PW
0    4.9  1.4  0.2
1    4.7  1.3  0.2
2    4.6  1.5  0.2
3    5.0  1.4  0.2
4    5.4  1.7  0.4
..   ...  ...  ...
144  6.7  5.2  2.3
145  6.3  5.0  1.9
146  6.5  5.2  2.0
147  6.2  5.4  2.3
148  5.9  5.1  1.8

[149 rows x 3 columns]

In [87]:
iris.pop('SW')

KeyError: 'SW'

In [79]:
iris

SL   PL   PW     Flower Type
0    4.9  1.4  0.2     Iris-setosa
1    4.7  1.3  0.2     Iris-setosa
2    4.6  1.5  0.2     Iris-setosa
3    5.0  1.4  0.2     Iris-setosa
4    5.4  1.7  0.4     Iris-setosa
..   ...  ...  ...             ...
144  6.7  5.2  2.3  Iris-virginica
145  6.3  5.0  1.9  Iris-virginica
146  6.5  5.2  2.0  Iris-virginica
147  6.2  5.4  2.3  Iris-virginica
148  5.9  5.1  1.8  Iris-virginica

[149 rows x 4 columns]

steps for data cleaning

.reading dataset
.rename the column name if required
.check missing values
.check data types
.check unique values
.check describe value
